In [3]:
import pandas as pd

In [4]:
matches = pd.read_csv('matches.csv')
matches.head()

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City

In [5]:
matches.shape

(1389, 28)

In [6]:
matches['team'].value_counts()

team
Manchester United           72
West Ham United             72
Newcastle United            72
Brighton and Hove Albion    72
Southampton                 72
Tottenham Hotspur           71
Manchester City             71
Leeds United                71
Wolverhampton Wanderers     71
Arsenal                     71
Crystal Palace              71
Burnley                     71
Chelsea                     70
Aston Villa                 70
Leicester City              70
Everton                     70
West Bromwich Albion        38
Fulham                      38
Liverpool                   38
Sheffield United            38
Brentford                   34
Norwich City                33
Watford                     33
Name: count, dtype: int64

In [7]:
matches[matches['team'] == 'Liverpool']

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
705,1,2020-09-12,17:30,Premier League,Matchweek 1,Sat,Home,W,4.0,3.0,...,Match Report,NaN,20.0,4.0,17.0,0.0,2.0,2.0,2021,Liverpool
706,2,2020-09-20,16:30,Premier League,Matchweek 2,Sun,Away,W,2.0,0.0,...,Match Report,NaN,17.0,5.0,17.7,1.0,0.0,0.0,2021,Liverpool
707,4,2020-09-28,20:00,Premier League,Matchweek 3,Mon,Home,W,3.0,1.0,...,Match Report,NaN,21.0,9.0,16.8,0.0,0.0,0.0,2021,Liverpool
708,6,2020-10-04,19:15,Premier League,Matchweek 4,Sun,Away,L,2.0,7.0,...,Match Report,NaN,14.0,8.0,15.8,1.0,0.0,0.0,2021,Liverpool
709,7,2020-10-17,12:30,Premier League,Matchweek 5,Sat,Away,D,2.0,2.0,...,Match Report,NaN,22.0,8.0,15.0,1.0,0.0,0.0,2021,Liverpool
710,9,2020-10-24,20:00,Premier League,Matchweek 6,Sat,Home,W,2.0,1.0,...,Match Report,NaN,17.0,5.0,18.2,1.0,0.0,0.0,2021,Liverpool
711,11,2020-10-31,17:30,Premier League,Matchweek 7,Sat,Home,W,2.0,1.0,...,Match Report,NaN,8.0,2.0,18.6,1.0,1.0,1.0,2021,Liverpool
712,13,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Away,D,1.0,1.0,...,Match Report,NaN,9.0,2.0,21.5,0.0,1.0,1.0,2021,Liverpool
713,14,2020-11-22,19:15,Premier League,Matchweek 9,Sun,Home,W,3.0,0.0,...,Match Report,NaN,24.0,12.0,11.9,0.0,0.0,0.0,2021,Liverpool
714,16,2020-11-28,12:30,Premier League,Matchweek 10,Sat,Away,D,1.0,1.0,...,Match Report,NaN,6.0,2.0,20.9,0.0,0.0,0.0,2021,Liverpool
715,18,2020-12-06,19:15,Premier League,Matchweek 11,Sun,Home,W,4.0,0.0,...,Match Report,NaN,11.0,6.0,16.6,1.0,0.0,0.0,2021,Liverpool
716,20,2020-12-13,16:30,Premier League,Matchweek 12,Sun,Away,D,1.0,1.0,...,Match Report,NaN,11.0,5.0,20.0,1.0,1.0,1.0,2021,Liverpool
717,21,2020-12-16,20:00,Premier League,Matchweek 13,Wed,Home,W,2.0,1.0,...,Match Report,NaN,17.0,11.0,15.5,0.0,0.0,0.0,2021,Liverpool
718,22,2020-12-19,12:30,Premier League,Matchweek 14,Sat,Away,W,7.0,0.0,...,Match Report,NaN,14.0,7.0,13.2,1.0,0.0,0.0,2021,Liverpool
719,23,2020-12-27,16:30,Premier League,Matchweek 15,Sun,Home,D,1.0,1.0,...,Match Report,NaN,17.0,2.0,17.8,2.0,0.0,0.0,2021,Liverpool
720,24,2020-12-30,20:00,Premier League,Matchweek 16,Wed,Away,D,0.0,0.0,...,Match Report,NaN,11.0,4.0,16.7,0.0,0.0,0.0,2021,Liverpool
721,25,2021-01-04,20:00,Premier League,Matchweek 17,Mon,Away,L,0.0,1.0,...,Match Report,NaN,17.0,1.0,14.3,0.0,0.0,0.0,2021,Liverpool
722,27,2021-01-17,16:30,Premier League,Matchweek 19,Sun,Home,D,0.0,0.0,...,Match Report,NaN,17.0,3.0,17.1,0.0,0.0,0.0,2021,Liverpool
723,28,2021-01-21,20:00,Premier League,Matchweek 18,Thu,Home,L,0.0,1.0,...,Match Report,NaN,27.0,6.0,17.3,0.0,0.0,0.0,2021,Liverpool
724,30,2021-01-28,20:00,Premier League,Matchweek 20,Thu,Away,W,3.0,1.0,...,Match Report,NaN,14.0,7.0,14.7,0.0,0.0,0.0,2021,Liverpool
725,31,2021-01-31,16:30,Premier League,Matchweek 21,Sun,Away,W,3.0,1.0,...,Match Report,NaN,14.0,5.0,15.3,0.0,0.0,0.0,2021,Liverpool
726,32,2021-02-03,20:15,Premier League,Matchweek 22,Wed,Home,L,0.0,1.0,...,Match Report,NaN,11.0,0.0,19.9,0.0,0.0,0.0,2021,Liverpool
727,33,2021-02-07,16:30,Premier League,Matchweek 23,Sun,Home,L,1.0,4.0,...,Match Report,NaN,7.0,2.0,17.9,1.0,1.0,1.0,2021,Liverpool
728,34,2021-02-13,12:30,Premier League,Matchweek 24,Sat,Away,L,1.0,3.0,...,Match Report,NaN,15.0,4.0,15.4,2.0,0.0,0.0,2021,Liverpool
729,36,2021-02-20,17:30,Premier League,Matchweek 25,Sat,Home,L,0.0,2.0,...,Match Report,NaN,16.0,6.0,15.9,1.0,0.0,0.0,2021,Liverpool
730,37,2021-02-28,19:15,Premier League,Matchweek 26,Sun,Away,W,2.0,0.0,...,Match Report,NaN,15.0,8.0,14.2,0.0,0.0,0.0,2021,Liverpool
731,38,2021-03-04,20:15,Premier League,Matchweek 29,Thu,Home,L,0.0,1.0,...,Match Report,NaN,7.0,1.0,18.4,0.0,0.0,0.0,2021,Liverpool
732,39,2021-03-07,14:00,Premier League,Matchweek 27,Sun,Home,L,0.0,1.0,...,Match Report,NaN,16.0,3.0,17.0,1.0,0.0,0.0,2021,Liverpool
733,41,2021-03-15,20:00,Premier League,Matchweek 28,Mon,Away,W,1.0,0.0,...,Match Report,NaN,12.0,4.0,15.9,0.0,0.0,0.0,2021,Liverpool
734,42,2021-04-03,20:00,Premier League,Matchweek 30,Sat,Away,W,3.0,0.0,...,Match Report,NaN,16.0,7.0,17.0,0.0,0.0,0.0,2021,Liverpool
735,44,2021-04-10,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,...,Match Report,NaN,23.0,8.0,16.7,1.0,0.0,0.0,2021,Liverpool
736,46,2021-04-19,20:00,Premier League,Matchweek 32,Mon,Away,D,1.0,1.0,...,Match Report,NaN,17.0,7.0,15.7,0.0,0.0,0.0,2021,Liverpool
737,47,2021-04-24,12:30,Premier League,Matchweek 33,Sat,Home,D,1.0,1.0,...,Match Report,NaN,21.0,9.0,17.0,1.0,0.0,0.0,2021,Liverpool
738,48,2021-05-08,20:15,Premier League,Matchweek 35,Sat,Home,W,2.0,0.0,...,Match Report,NaN,14.0,6.0,12.4,0.0,0.0,0.0,2021,Liverpool
739,49,2021-05-13,20:15,Premier League,Matchweek 34,Thu,Away,W,4.0,2.0,...,Match Report,NaN,17.0,8.0,14.9,0.0,0.0,0.0,2021,Liverpool
740,50,2021-05-16,16:30,Premier League,Matchweek 36,Sun,Away,W,2.0,1.0,...,Match Report,NaN,26.0,6.0,16.9,1.0,0.0,0.0,2021,Liverpool
741,51,2021-05-19,20:15,Premier League,Matchweek 37,Wed,Away,W,3.0,0.0,...,Match Report,NaN,20.0,3.0,15.5,1.0,0.0,0.0,2021,Liverpool
742,52,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,2.0,0.0,...,Match Report,NaN,19.0,5.0,14.2,1.0,0.0,0.0,2021,Liverpool

In [8]:
matches.dtypes

Unnamed: 0        int64
date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [9]:
matches['date'] = pd.to_datetime(matches['date'])

In [11]:
matches['venue_code'] = matches['venue'].astype('category').cat.codes

In [12]:
matches['opp_code'] = matches['opponent'].astype('category').cat.codes

In [13]:
matches['hour'] = matches['time'].str.replace(':.+', '', regex=True).astype(int)

In [14]:
matches['day_code'] = matches['date'].dt.dayofweek

In [18]:
matches['target'] = (matches['result'] == 'W').astype(int)

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [22]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

train = matches[matches['date'] < '2022-01-01']
test = matches[matches['date'] >= '2022-01-01']
predictors = ['venue_code', 'opp_code', 'hour', 'day_code']

rf.fit(train[predictors], train['target'])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [ ]:
preds = rf.predict(test[predictors])
acc = accuracy_score(test['target'], preds)
acc

0.6134751773049646

In [26]:
combined = pd.DataFrame(dict(actual=test['target'], prediction=preds))
pd.crosstab(index=combined['actual'], columns= combined['prediction'])

prediction    0   1
actual
0           144  31
1            78  29

In [27]:
precision_score(test['target'], preds)

0.48333333333333334

In [28]:
grouped_matches = matches.groupby('team')
group = grouped_matches.get_group('Arsenal')
group

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
65,0,2021-08-13,20:00,Premier League,Matchweek 1,Fri,Away,L,0.0,2.0,...,1.0,0.0,0.0,2022,Arsenal,0,2,20,4,0
66,1,2021-08-22,16:30,Premier League,Matchweek 2,Sun,Home,L,0.0,2.0,...,0.0,0.0,0.0,2022,Arsenal,1,5,16,6,0
67,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Away,L,0.0,5.0,...,0.0,0.0,0.0,2022,Arsenal,0,12,12,5,0
68,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,1.0,0.0,...,1.0,0.0,0.0,2022,Arsenal,1,15,15,5,1
69,5,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Away,W,1.0,0.0,...,1.0,0.0,0.0,2022,Arsenal,0,4,15,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,52,2021-05-02,14:00,Premier League,Matchweek 34,Sun,Away,W,2.0,0.0,...,1.0,0.0,0.0,2021,Arsenal,0,14,14,6,1
929,54,2021-05-09,19:00,Premier League,Matchweek 35,Sun,Home,W,3.0,1.0,...,1.0,0.0,0.0,2021,Arsenal,1,20,19,6,1
930,55,2021-05-12,20:15,Premier League,Matchweek 36,Wed,Away,W,1.0,0.0,...,0.0,0.0,0.0,2021,Arsenal,0,5,20,2,1
931,56,2021-05-19,19:00,Premier League,Matchweek 37,Wed,Away,W,3.0,1.0,...,0.0,0.0,0.0,2021,Arsenal,0,6,19,2,1
932,57,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,2.0,0.0,...,1.0,0.0,0.0,2021,Arsenal,1,3,16,6,1

In [29]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values('date')
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [30]:
cols = ['gf', 'ga', 'sh', 'sot', 'dist', 'fk', 'pk', 'pkatt']
new_cols = [f'{c}_rolling' for c in cols]

In [31]:
rolling_averages(group, cols, new_cols)

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
898,6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,...,6,1,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
899,7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,...,5,0,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
900,9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,...,6,0,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
901,11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,...,6,1,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
902,13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,...,6,0,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,35,2022-04-04,20:00,Premier League,Matchweek 31,Mon,Away,L,0.0,3.0,...,0,0,1.000000,0.666667,13.000000,3.666667,18.400000,0.000000,0.333333,0.333333
94,36,2022-04-09,15:00,Premier League,Matchweek 32,Sat,Home,L,1.0,2.0,...,5,0,0.333333,1.666667,10.333333,2.666667,19.300000,0.000000,0.000000,0.000000
95,37,2022-04-16,15:00,Premier League,Matchweek 33,Sat,Away,L,0.0,1.0,...,5,0,0.666667,1.666667,14.000000,3.333333,17.566667,0.666667,0.000000,0.000000
96,38,2022-04-20,19:45,Premier League,Matchweek 25,Wed,Away,W,4.0,2.0,...,2,1,0.333333,2.000000,18.333333,4.333333,17.400000,1.000000,0.000000,0.000000
97,39,2022-04-23,12:30,Premier League,Matchweek 34,Sat,Home,W,3.0,1.0,...,5,1,1.666667,1.666667,18.666667,4.333333,17.900000,1.000000,0.333333,0.333333

In [33]:
matches_rolling = matches.groupby('team').apply(lambda x: rolling_averages(x, cols, new_cols)).droplevel('team')
matches_rolling

C:\Users\vasco\AppData\Local\Temp\ipykernel_17544\760969777.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  matches_rolling = matches.groupby('team').apply(lambda x: rolling_averages(x, cols, new_cols)).droplevel('team')

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
898,6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,...,6,1,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
899,7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,...,5,0,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
900,9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,...,6,0,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
901,11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,...,6,1,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
902,13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,...,6,0,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,32,2022-03-13,14:00,Premier League,Matchweek 29,Sun,Away,W,1.0,0.0,...,6,1,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
228,33,2022-03-18,20:00,Premier League,Matchweek 30,Fri,Home,L,2.0,3.0,...,4,0,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
229,34,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,...,5,1,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
230,35,2022-04-08,20:00,Premier League,Matchweek 32,Fri,Away,L,0.0,1.0,...,4,0,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
231,36,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,L,0.0,1.0,...,6,0,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [34]:
matches_rolling.index = range(matches_rolling.shape[0])

In [35]:
def make_predictions(data, predictors):
    train = data[data['date'] < '2022-01-01']
    test = data[data['date'] >= '2022-01-01']
    rf.fit(train[predictors], train['target'])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test['target'], prediction=preds), index=test.index)
    precision = precision_score(test['target'], preds)
    return combined, precision

In [36]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)
precision

0.625

In [37]:
combined = combined.merge(matches_rolling[['date', 'team', 'opponent', 'result']], left_index=True, right_index=True)

In [38]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {
    'Brigthon and Hove Albion': 'Brighton',
    'Manchester United': 'Manchester Utd',
    'Newcastle United': 'Newcastle Utd',
    'Tottenham Hotspur': 'Tottenham',
    'West Ham United': 'West Ham',
    'Wolverhampton Wanderers': 'Wolves',
}

mapping = MissingDict(**map_values)

In [39]:
combined['new_team'] = combined['team'].map(mapping)

In [40]:
merged = combined.merge(combined, left_on=['date', 'new_team'], right_on=['date', 'opponent'])